SaxoBank/openapi-clientlib-js

README.md

More verbose description of external dependencies required for this library to function.
Previous description could be read as description of production content of package.json.

More verbose description of external dependencies

---

grunt/print-task.js

We don't have minitrader grunt task in this project, so it shouldn't be part of result when printing all available grunt commands/tasks.
Fixes #11

Removed reference to minitrader in print-task

---

npm-shrinkwrap.json
package.json

Version of grunt-contrib-jasmine that we use had issue with printing exceptions due to missing _.sprintf:
https://github.com/gruntjs/grunt-contrib-jasmine/issues/232
I've bumped version to 1.0.3 which has fix for this issue and doesn't use deprecated solution (1.0.2 doesn't).

Bump grunt-contrib-jasmine version to fix issue with missing _.sprintf

---

grunt/jshint-conf.js
grunt/print-task.js
gruntfile.js

Added new jshint rule to disallow console.
Removed existing console.log usage and replaced it with grunt.log.

JSHint: Disallow console usage.

---

src/number-formatting/format.js
test/unit/number-formatting/format-spec.js
test/unit/price-formatting/format-spec.js

Adds the possibility to format values on scientific notation.
A value such as `0.0000005` is automatically converted to `5e-7` on javascript. Number format would then pick convert the value to a string and the output would be something completely wrong - i.e `5,e-7`.
This fix parses the scientific notation value and adds the correct amount of zeros to then allow the formatter to do his normal steps.

Add formatting scientific notation's values support

---

src/number-formatting/short-format.js
test/unit/number-formatting/format-spec.js

NumberFormatting.shortFormat didn't support decimals properly. Specifically, some floating points gave issues such as 1000000.11 => 0m. This fixes the issue by calculating the boundary from digit size.
Fixes #48

Add support for decimal values to NumberFormatting.shortFormat

---

src/utils/fetch.js
test/unit/mocks/fetch.js
test/unit/utils/fetch-spec.js

This will allow fetch to handle binary responses when content-type is a pdf or an excel sheet.

allow fetch to handle binary responses when content-type is a pdf or an excel sheet

---

src/number-formatting/number-formatting.js
src/number-formatting/short-format.js
test/unit/number-formatting/format-spec.js

Add precision parameter to short formatter
In some cases, short formatted numbers require custom precision. Developers should be able to define, with what precision shortened number should be returned.
The new signature of `shortFormat ` should be compatible with previous usages. To guarantee that a check for the presence of `precision` parameter is done. If the parameter is not present, the function will calculate the precision in the old way.

 Add precision parameter to short formatter

---

src/price-formatting/format.js
test/unit/price-formatting/format-spec.js

issue: #59  Infinitesimally small negative value is rounded to 0 and the value returned is -0 or 0-, which is unexpected
Fix: if the format value is zero removing the '-' sign

adding check for negative zero in case of formatting infinitesimally small negative values

---

src/number-formatting/format.js
src/number-formatting/number-formatting.js
src/number-formatting/short-format.js
test/unit/number-formatting/format-spec.js

Short formatter remove 'zero tails' by default
Short formatter should not allow manually set precision for formatted numbers but when shortened number has tail only from `0` digits (ex. `10.00k` / `50.0k` etc.) it should be removed (`10.00k` into `10k` / `50.0k` into `50k`).
The `expandNumber` function has a new option flag, which is turned on by default for `shortFormat` function (we want to keep the result of the short format as short as possible). This flag prevents displaying of the floating part (only when made of `0` digits) and unnecessary related calculations.

Short formatter remove 'zero tails' by default

---

src/openapi/transport/retry.js
src/utils/fetch.js

If there is a network disconnection, stop the transport from retrying

If there is a network disconnection, stop the transport from retrying

---

src/openapi/streaming/streaming.js

Clearing reconnect timeout upon connection and multiple consecutive reconnects.
Currently, reconnect timeouts are left hanging after they are fired. In some scenarios this can cause unnecessary firing of reconnects logic.

Clear reconnect timeout 

---

src/openapi/transport/auth.js
src/utils/fetch.js
test/unit/openapi/transport/auth-spec.js
test/unit/openapi/transport/core-spec.js
test/unit/utils/fetch-spec.js

- Retry oAuth token refresh before triggering fail event. This should only happen if the error is caused by a network failure, and not if the response code is 401 or 403.
- Better logging when a fetch calls results in an error

Improve logging and refresh retrying logic in case of network errors

---

src/openapi/streaming/subscription.js
test/unit/openapi/streaming/subscription-spec.js

Some openapi endpoints don't support protobuf (at this point only one).
If protobuf is not supported by specific endpoint, try to subscribe using default json format.
Do it only once per subscription instance.

Fallback support for protobuf requests.

---

src/openapi/transport/auth.js
test/unit/openapi/transport/auth-spec.js
test/unit/utils.js

Fix introduces guard for maximum authorization fails that can happen within defined period of time (with debounce).
So for example if specific authorization endpoint fails 3 times, where each fail was within 5s timeframe, we block further error handling for this endpoint, until more then 5s passes.
This blocks further loop of endpoint errors and oauth re-requests.
Generally, scenario being fixed here is edge case end should never happen by design. However we had cases where openapi errors caused specific endpoint to always return 401 when requested.
By desing, on our side, if authorization error is returned for specific endpoint (which my happen by design), we request fresh authorization token. However, if endpoint is broken, and returns 401 for valid, fresh authorization tokens, we were …

Add authorization error (401) limits to block infinite loop of auth token requests

---

src/utils/fetch.js

Adds request ID passed from OpenAPI to the error logging.
Note: The header name might change after discussion with the OpenAPI teams.
Internal PR #: 30747

feat: add Request ID from OpenAPI to error logging

---

src/openapi/transport/auth.spec.js
src/openapi/transport/core.spec.js
src/utils/fetch.js

Change: Default body to empty object for PATCH requests without body
Reason: Some proxies and default configs for CDNs like Akamai have issues with accepting PATCH with content-length: 0.

Default body to empty object for PATCH requests without body.

---

package.json
src/openapi/streaming/subscription.js
src/openapi/streaming/subscription.spec.js

Fix for protobuf logic.
Currently when endpoint doesn't support protobuf, endpoint returns an error and openapi-clientlib fallbacks to json subscription.
However in addition to a subscribe, we also send an error message which in our GO sagas drops/locks subscription from further passing updates.
To be backward compatible, I've dropped invoking error callbacks when endpoint fails due to protobuf format being unsupported.
This ensure that userspace can keep current error handling logic with duplicated code need for handling protobuf errors.
So in short. Due to error being inreversible/fatal one, we only now send it whenever subscription fails without fallback. However in fallback scenarios fatal error isn't sent.
If we decide to keep error being invoked, we should then drop re-connect logic …

Bug protobuf fallback logic

---

src/openapi/streaming/streaming.js
src/openapi/streaming/subscription.js

Added an optional `onQueueEmpty` callback to the subscription. 
This will be called after the action queue goes from 1 to 0 items, indicating that the client is done processing actions.

add onQueueEmpty callback to subscription

---

src/openapi/streaming/streaming.js
src/openapi/streaming/subscription.js
src/openapi/streaming/subscription.spec.js

In order to enable headers in subscription requests, add options to the createSubscription method. To clean up a bit, move optional methods inside the options parameter as well.

Add subscription options

---

src/openapi/streaming/subscription.js
src/openapi/streaming/subscription.spec.js

Some transports may append to the headers object. This can cause trouble since it will mutate the passed `options.headers` object.
This change creates a new `headers` object before passing it on, avoiding potential for mutation.

avoid mutating header options

---

src/utils/fetch.js
src/utils/fetch.spec.js

Since the recommended action for an implementation that receives an "application/octet-stream" entity is to simply offer to put the data in a file,
Adding support for `application/octet-stream` in binaryContentTypes list for data to be treated as binary blobs.

Adding support for 'application/octet-stream' content type

---

src/openapi/transport/auth.js

I think I wrote the existing code and when I went back to it recently it confused me - I initially thought it was sending an error log when the token was expired..
I hope the new verbose name is clearer.

make Invalid variable name clearer

---

src/openapi/streaming/streaming.js
src/openapi/streaming/streaming.spec.js

Add delay levels for streaming total reconnects.
Allows client to provide various delay levels for specific retry counts levels. 
Example Structure and documented side effects on delays:
```
[
{ level: 0, delay: 1000 }, // First reconnect will wait 1s.
{ level: 1, delay: 2000 }, // Second reconnect will wait 2s.
{ level: 5, delay: 3000 }, // From second reconnect to 4th one, we will use 2s delay, and from 5th up to infinity, 3s delay would be used.
]
```

Add delay levels for streaming total reconnects.

---

src/openapi/streaming/streaming.js
src/openapi/streaming/streaming.spec.js

Set default value for retryCount. Otherwise it's possible it will have NaN value forever, even after increments.

Set default value for retryCount

---

src/price-formatting/format-options.js
src/price-formatting/format.js
src/price-formatting/format.spec.js

Adds a new format flag `UseExtendedDecimals` which will add up to 8 non-zero decimals beyond the requested number of decimals. The extra decimals will be part of either First/Pips or DeciPips depending on presence of `AllowDecimalPips`.
To support internal user story 1163324 and the PR I'm about to create for it, see there for context.
I've temporarily committed the `dist` folder to allow adding this branch as a Yarn dependency direct from GitHub, so probably don't need a beta version published.
@michax

Allow formatting price up to 8 decimals

---

src/openapi/streaming/connection/transport/websocket-transport.js
src/openapi/streaming/connection/transport/websocket-transport.spec.js

Fixes:
- null contextId while reconnecting.
- Fixes reconnection logic. i.e. don't fire disconnect event unless reconnect timeout is over
- Handle 1002 on close. i.e. re-authorise if token expired

Fix websocket transport

---

changelog.md
package.json
src/openapi/authProvider.js
src/openapi/batch-util.js
src/openapi/streaming/connection/connection.js
src/openapi/streaming/connection/constants.js
src/openapi/streaming/connection/transport/signalr-transport.js
src/openapi/streaming/connection/transport/signalr-transport.spec.js
src/openapi/streaming/connection/transport/websocket-transport.js
src/openapi/streaming/connection/transport/websocket-transport.spec.js
src/openapi/streaming/orphan-finder.js
src/openapi/streaming/parser/parser-protobuf.js
src/openapi/streaming/streaming-websocket.spec.js
src/openapi/streaming/streaming.js
src/openapi/streaming/streaming.spec.js
src/openapi/streaming/subscription.js
src/openapi/streaming/subscription.spec.js
src/openapi/transport/auth.js
src/openapi/transport/auth.spec.js
src/openapi/transport/batch.js
src/openapi/transport/putPatchDiagnosticsQueue.js
src/utils/fetch.js

I've reviewed all logs - Searching for occurrences of our errors/warns and evaluating whether they should be a error/warning on the basis that error/warns should be indications that something is gone wrong that is abnormal. If a network error occurs or a fairly normal event that isn't a problem occurs, including the effect of a single open api server going down and subscriptions failing over then it should not be a warn/error.

Revew log messages and improve network resiliency

---

.eslintignore
.prettierignore
changelog.md
package-lock.json
package.json
src/openapi/streaming/parser/parser-facade.js
src/openapi/streaming/streaming-websocket.spec.js
src/openapi/streaming/streaming.js
src/openapi/streaming/streaming.spec.js
src/openapi/streaming/subscription.js
src/openapi/streaming/subscription.spec.js
src/openapi/transport/auth.js
src/openapi/transport/auth.spec.js
src/openapi/transport/batch.js
src/openapi/transport/batch.spec.js
src/openapi/transport/core.js
src/openapi/transport/core.spec.js
src/openapi/transport/queue.js

Capability to configure particular services as cloud services. This sends them to `/oapi` rather than `/openapi`, and excepts them from HTTP-level batching.
```javascript
new SomethingTransport('https://www.saxotrader.com', {
services: {
'fooservice': { useCloud: true }  
}
});
```
Service groups don't exist in the cloud so it's no longer universal. It only remains as a concept in the batch transport for on-prem only. Elsewhere it's just a path string with no particular meaning, so it's renamed to service path to reflect it could be either a service group or the name of a cloud service (causes a lot of diff noise after the first few commits).
In future we may extend the config with a `useBatching` option to allow our "modern services" to be run on-prem where they probably won't have …

Support cloud services

---

changelog.md
package.json
src/openapi/streaming/connection/transport/websocket-transport.js
src/openapi/streaming/connection/transport/websocket-transport.spec.js

If there is a random socket disconnect there is no reason to wait 2s before disconnecting on the first disconnect.
After that its important we wait as we only retry x number of times and if we don't delay we use up the connection attempts.

reduce connection delay

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/connection/transport/signalr-core-transport.js
src/openapi/streaming/connection/transport/signalr-core-transport.spec.js
src/openapi/streaming/streaming.js

This PR modifies reconnection logic to send last received message id while reconnecting.
Last received message id is sent as query string while trying to reconnect again.
Server will return _reconnect control message if session is not found while trying to reconnect. In this case client will disconnect and try to reconnect with new context id.

Send last received message id while reconnecting

---

src/number-formatting/format.js
src/price-formatting/format.spec.js

**Desription**
For some numbers when calling format functions (ex: priceFormatting.format), the number was rounded down while it should be up. 
Example: 
priceFormatting.format(1.005, 2) is returning 1.00 while it should be 1.01.
The issue is caused by binary floating-point representation. 
Example: 
- 0.1 + 0.2 !== 0.3
- 1.005 * 100 = 100.49999999999999
More about it:
https://www.codemag.com/Article/1811041/JavaScript-Corner-Math-and-the-Pitfalls-of-Floating-Point-Numbers
**Solution**
Changing the rounding to use the numbers represented in exponential notation.
http://www.jacklmoore.com/notes/rounding-in-javascript/
Example:
1.005 * 100 is converted to 1.005e2 which gives us 100.5 in a non exponential notation.
**Test**
Added unit test for the above example priceFormatting.format(1.005, …

Bug fix rounding decimals formatters

---

changelog.md
package-lock.json
src/openapi/transport/batch.js
src/openapi/transport/core.js
src/openapi/transport/core.spec.js
src/openapi/transport/options.js

Support the use case of gradual rollout of a replacement service having the same servicePath.

Allow useCloud to be a function

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/connection/transport/signalr-core-transport.js
src/openapi/streaming/connection/transport/signalr-core-transport.spec.js

If consumer app has fetch polyfill for IE11, Signalr core lib tries to use FetchHttpClient for communication which uses AbortController. Unfortunately AbortController is not supported in IE11. Signalr do use ponyfill for AbortController except in FetchHttpClient. I have raise a bug in signalr repo for the same.
https://github.com/dotnet/aspnetcore/issues/29424
This PR also fixes the token renewal issue. It was possible to call renewSession before the connection is established.
The guard is added to check whether connection is established before calling renewSession

Fix exception in IE11 and token renewal issue

---

.eslintrc
changelog.md
package.json
src/openapi/transport/auth.js
src/openapi/transport/auth.spec.js
src/openapi/transport/batch.js
src/openapi/transport/batch.spec.js
src/utils/fetch.js

From analyzing logs on live I've found some bugs - primarily the problem is that isNetworkError is false when it should be true for alot of batch requests.
When I found the issue, I realised that we should not be getting this error at all under normal operation, so analysing that I found that when calls are delayed it can trigger the authorisation error overload when the calls were dispatched many minutes apart. So I fixed that by debouncing calls based on the time from when the request starts.

Fix various minor issues

---

changelog.md
package.json
src/openapi/streaming/subscription-actions.js
src/openapi/streaming/subscription-queue.js
src/openapi/streaming/subscription-queue.spec.js
src/openapi/streaming/subscription.js
src/openapi/streaming/subscription.spec.js

1. When we get a reset, unsubscribe and wait for that subscribe to finish before subscribing again
2. As a side effect - resets occurrring whilst unsubscribing have no effect
3. Because we could be in the process of subscribing so unsure if the subscription is reset or not.. we need to make sure we force a unsubscribe - so added a force option to unsubscribe
4. The force option on unsubscribe is the same as the existing modify_subscribe logic - its achieving the same thing by making sure a unsubscribe/subscribe happens. So remove that action type and rely on force unsubscribe.
5. Re-write the queue to handle this. Also try and reduce calls that might happen because we get a modify patch when in the unsubscribed state

Handle reset better

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/connection/connection.js
src/openapi/streaming/connection/constants.js
src/openapi/streaming/connection/transport/signalr-core-transport.js
src/openapi/streaming/connection/transport/signalr-core-transport.spec.js
src/openapi/streaming/connection/transport/websocket-transport.js
src/openapi/streaming/connection/transport/websocket-transport.spec.js
src/openapi/streaming/streaming.js
src/openapi/streaming/streaming.spec.js
src/openapi/streaming/subscription-queue.js
src/openapi/streaming/subscription.js

- Handle disconnect by logging user off
- Handle reconnect and service switching by unsubscribing all subscriptions, stop streaming, start and then re-subscribe
- Check for token expiry during reconnection
- Add more logs and guards

Fix streaming issues

---

changelog.md
package.json
src/number-formatting/format.js
src/price-formatting/format.spec.js

**Desription**
For some numbers when calling format functions (ex: priceFormatting.format), the number was rounded down while it should be up.
**Example:**
priceFormatting.format(1.005, 2) is returning 1.00 while it should be 1.01.
The issue is caused by binary floating-point representation.
**Example:**
0.1 + 0.2 !== 0.3
1.005 * 100 = 100.49999999999999
More about it:
https://www.codemag.com/Article/1811041/JavaScript-Corner-Math-and-the-Pitfalls-of-Floating-Point-Numbers
**Solution**
Changing the rounding to use the numbers represented in exponential notation. First multiply using exponential notation, round, and then divide by numeric factor representation
**Example:**
1.005 with 2 decimals is converted to 1.005e2 which gives us 100.5 in a non exponential notation, rounded to 101, and …

Bug rounding number

---

changelog.md
package-lock.json
package.json
src/openapi/transport/core.js
src/openapi/transport/core.spec.js
src/utils/fetch.js

We sometimes (eg when user logs out while requests are being made) need to abort fetch requests. This PR adds possibility to use abort signal (returned by AbortController), so it can be handled without hacks.

Add option to pass abort signal

---

src/openapi/streaming/streaming.ts

This PR disables persistance of the `Connection state change` event (TFS work item: 1345143)

Do not persist connection state change log

---

changelog.md
package.json
src/number-formatting/format.spec.ts
src/number-formatting/index.ts

Why?
`formatNoRounding` function is appending 0 values(uptil 8 decimal) for large numbers. 
- Reason - `getActualDecimals`  is returning incorrect decimal length due to `number-Math.float(number)`  and `toFixed` which  approximate value due to floating precision 
- In case of  `formatNoRounding(92893282191.78,2)`, getActualDecimal will return the decimal part `"0.77999878"` as toFixed(8) is not able to roundoff (Thus length 8) and we get `'92893282191.78000000'` which is wrong.
Soln
- Will adjust constant 8 that is passed to `toFixed`.
- Browser start rounding off(precision) decimal number after 16-17 chars. So by subtracting const 16(taking assumption) with non-decimal places of number we can get the actual decimal place where the browser is able to round off correctly.

Enhanced getActualDecimals function 

---

src/openapi/streaming/connection/connection.ts
src/openapi/streaming/connection/transport/websocket-transport.spec.ts
src/openapi/streaming/connection/transport/websocket-transport.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/types.ts

- Due to the fact that browsers may disconnect web-socket connection without knowing so, we need to add a heartbeat protocol on top of web-socket in the web-socket streaming service.
- To enable heartbeats on a connection (or reconnection) the following query parameter must be added to the connection URL: **&sendHeartbeats=true**
- The heartbeat messages follow the usual control message format, so they come with the reference id **_connectionheartbeat**
-  So by sending the "sendHeartbeats=true" as queryParam a connection heartbeat is sent after 2 seconds of inactivity on a streaming connection, i.e. when there has been no heartbeat or other streaming message for 2 seconds
- In this change we try to reconnect the web socket if we don't receive any message on the web socket for 2.5 seconds …

websocket transport streaming heartbeat added

---

src/openapi/streaming/streaming.ts

by passing the whole subscription, when we do JSON stringify, it can hit a circular reference.

Fix circlular log message

---

src/openapi/streaming/connection/transport/websocket-transport.ts

this is the continuation of this pr: https://github.com/SaxoBank/openapi-clientlib-js/pull/416
earlier we are passing the sendHeartbeats query param in the update query method which get invoked when we reconnect or some failure happens but it doesn't add sendHeartbeats on initial ws socket creation for success case.
so moving the logic to create ws function which gets invoked in call cases.

streaming heartbeat query param on create of ws

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/connection/transport/signalr-core-transport.ts
src/openapi/streaming/connection/transport/websocket-transport.ts
src/openapi/streaming/control-messages.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/types.ts

1. do not log a error when it is a normal situation (reconnecting without last message id failed)
2. make sure when reconnecting we use a last message id (extra call to update query)
3. If the context changes we cannot re-use the last message id, so clear it

websocket - Last message id fixes

---

changelog.md
package-lock.json
package.json
src/openapi/authProvider.spec.ts
src/openapi/transport/core.spec.ts
src/utils/fetch.ts

This PR makes an http method name passed to fetch uppercase.
See https://bugs.chromium.org/p/chromium/issues/detail?id=1228178

Convert HTTP method names passed to fetch to uppercase

---

src/openapi/streaming/streaming.spec.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/subscription.spec.ts
src/openapi/streaming/subscription.ts
src/openapi/streaming/types.ts

- As of now we queue subscription requests waiting for streaming and only when streaming setup is done we allow it to subscribe.
- setting up streaming connection takes time because of which our subscription also have to wait for it.
- this PR adds an option to pass a Boolean flag **shouldSubscribeBeforeStreamingSetup** while creating a new subscription. 
- when this flag is passed true we will not wait for streaming connection to setup and will subscribe right away. by doing this we can get the initial snapshot response which we can use to render our UI as early as possible.
- later updates will be passed via the streaming channel when its ready

Subscribe before streaming setup

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/streaming-websocket.spec.ts
src/openapi/streaming/streaming.spec.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/subscription-actions.ts
src/openapi/streaming/subscription-queue.spec.ts
src/openapi/streaming/subscription-queue.ts
src/openapi/streaming/subscription.spec.ts
src/openapi/streaming/subscription.ts

This creates a new subscription and deletes the old one in a single HTTP request.
This is:
* safer than doing a delete and create in parallel, which can hit subscription limits
* faster than waiting for the delete to return before doing the create
`PATCH` is still the preferred and most efficient full-stack way of modifying arguments, but this new option deals with the reality that many services haven't implemented it.
Internal accompanying PR: 130056

Add subscription modify option to use ReplaceReferenceId

---

src/openapi/streaming/subscription.ts

We have many errors (with muted alerts) for "unanticipated state in X", but only a few of them have the necessary context info to be able to investigate them.
I'm not anticipating releasing this now - it can probably go with the next one.

Include contextual information in all "unanticipated state" error logs

---

src/openapi/streaming/connection/transport/websocket-transport.spec.ts
src/openapi/streaming/connection/transport/websocket-transport.ts
src/openapi/streaming/control-messages.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/types.ts

incremental message id logic was introduced in this pr: [458](https://github.com/SaxoBank/openapi-clientlib-js/pull/458/)
`_connectionheartbeat` type heart beat message don't have incremental message id implementation so these type of message are logging error.
to fix this in this pr we are just skipping `_connectionheartbeat` type messages from in the incremental message id logic.

fixed _connectionheartbeat msg id issue

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/parser/parser-protobuf.ts
src/openapi/streaming/subscription.ts

We agreed that in order to fix a issue with open api rollout changing the SchemaName, we need to include only the schema name in all responses. But this is breaking the app because we only set this.SchemaName when both schema name and schema is present.

fix protobuf issue

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/streaming.spec.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/types.ts

Add tests for the current message format.
Add tests and support for the new message format.
Log warnings when unsupported messages are found to find problems more quickly.

Support cloud streaming control message format

---

src/openapi/streaming/connection/connection.ts
src/openapi/streaming/connection/transport/signalr-core-transport.spec.ts
src/openapi/streaming/connection/transport/signalr-core-transport.ts
src/openapi/streaming/connection/types.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/types.ts

BUG 1448366 -  Reset all subscriptions when we get a missing message id, initial logic to review

#1448366 reset all subscription is missing message

---

src/openapi/streaming/connection/transport/signalr-core-transport.ts

This error occurs when there is a network error, so making it a warning rather than a error.

Make streaming error log a warning

---

changelog.md
package.json
src/openapi/streaming/connection/transport/websocket-transport.spec.ts
src/openapi/streaming/connection/transport/websocket-transport.ts

We saw several thousand unhandled rejections occur when a network error was occurring trying to authorize. Whilst not a problem, this change aims to reduce the amount of noise we get when this happens.

Prevent a unhandled rejection and add a buffer for network retry

---

changelog.md
package-lock.json
package.json
src/openapi/authProvider.spec.ts
src/openapi/authProvider.ts

In case of a token refresh failure due to authorization error we expose the status with which the request failed. Based on that info different actions on the consumer side can be undertaken.
Adds test covering 407 status code (proxy authentication error).

Expose token refresh failure status

---

.eslintrc
src/openapi/streaming/streaming-websocket.spec.ts
src/openapi/streaming/streaming.spec.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/subscription-actions.ts
src/openapi/streaming/subscription.spec.ts
src/openapi/streaming/subscription.ts

In a connection outage if disposeSubscription is called, then the subscription does nothing as it is in a connection unavailable state, then it is removed from the list of subscriptions, so it is never made available and unsubscribe is never called, leading to hanging subscriptions.
Solution - make a new action for removing so that it is only removed once the existing queue is clear.

Fix a bug with removing during connection issues

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/connection/transport/websocket-transport.spec.ts
src/openapi/streaming/connection/transport/websocket-transport.ts
src/openapi/streaming/streaming.ts

- Remove streaming heartbeat flag, making it present for all suitable requests.
- Bump version
SaxoTrader PR: #155503 
This is based on Himashu's PR: https://github.com/SaxoBank/openapi-clientlib-js/pull/538
Created a new one as I didn't have access to his repo to rebase on the newest master.

Remove streaming heartbeat flag

---

changelog.md
package-lock.json
package.json
src/utils/fetch.spec.ts
src/utils/fetch.ts

We have a number of 204 responses where we log a warning about no content type.
Since 204 means no content, we can assume we do not need to process the content.

assume no content if 204

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/subscription.spec.ts
src/openapi/streaming/subscription.ts

If we keep the state as subscribed when we error then retries (protobuf error / network error) will not happen, they will be ignored as the state will still be subscribed and subscribe on a subscribed state is a no-op.

Fix potential subscription error handling issue

---

changelog.md
package.json
src/openapi/streaming/subscription-actions.ts
src/openapi/streaming/subscription-queue.ts
src/openapi/streaming/subscription.spec.ts
src/openapi/streaming/subscription.ts

When a subscription is reset, if it is waiting for a patch to be processed it has a "optimisation" where it sets the state to subscribed and calls unsubscribe. This then sets the state to unsubscribe requested and subscribe is queued.
However because the state is not transitioning, unsubscribe is not queued, so the queue does not remove patches (the queue will say, adding unsubscribe where patches are queued means the patches are not needed).
In addition the patch request, when it returns, with either a error or a success will, if the reference id hasn't changed (which it probably won't because unsubscribe hasn't come back yet), set the state to subscribed and continue to call the next item in the queue, which might be another patch. The unsubscribe comes back and sets the state to …

Fix unanticipated state errors

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/subscription.spec.ts
src/openapi/streaming/subscription.ts

Another error is caused because the waiting for publisher state is set but we might be waiting for a patch to complete, so the state will get overridden with a subscribed state, taking us out of waiting for publisher. We may also do a reset when not needed, but again this is low impact.
Because the code bypasses waiting for publisher when we try and unsubscribe (try perform action), it might have items in the queue, but these are ignored (usually items in the queue must mean transitioning state, meaning we only add to the queue), it means that we process the unsubscribe, but we may have subscribe in the queue, so we do that after the unsubscribe. e.g.
1. waiting for publisher
2. call subscribe
3. call unsubscribe & remove
4. unsubscribe is processed
5. the subscribe is processed
6. the …

Remove waiting for publisher state

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/subscription.spec.ts
src/openapi/streaming/subscription.ts

Fix an issue if a modify occurs whilst waiting to retry a subscription that failed due to a network issue, then it would just log a error and not attempt a re-subscribe.
I thought this was covered in tests but it only covered the modify that is subscribe/unsubscribe. not replace mode or patch.

Fix modify after network error

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/streaming-websocket.spec.ts
src/openapi/streaming/streaming.spec.ts
src/openapi/streaming/streaming.ts
src/openapi/streaming/subscription-queue.ts
src/openapi/streaming/subscription.spec.ts
src/openapi/streaming/subscription.ts

We are getting some data updates after calling remove. After investigation the queue is modify replace, unsubscribe (not force) and because of a bug it is not removing the queue to end up with unsubscribe (force) so that the update is not sent to the subscriber.

Fix remove not disabling data update

---

changelog.md
package-lock.json
package.json
src/openapi/streaming/connection/constants.ts
src/openapi/streaming/orphan-finder.ts
src/openapi/streaming/streaming.spec.ts
src/openapi/streaming/streaming.ts

A year ago we added detection of orphans and then consumers could reconnect on the event.
This pr brings the reconnect directly into the client library and 1) fixes a bug that we aren't resetting orphan data after a reconnect 2) adds a condition to ignore the issue if we received a recent update

Fix reconnect on detecting orphans

---

changelog.md
package.json
src/openapi/streaming/subscription.ts

Came from investigating why we have to many orphan logs. In conseqence this shouldn't have much of a end user effect, except it might be longer before the subscription is reset (because the orphan finder won't reset it)

Fix orphan issue
