CONTRIBUTING.md
Fixed formatting issue in CONTRIBUTING.md
=> Fixed formatting issue in CONTRIBUTING.md

npm-shrinkwrap.json, package.json
also fixes a typo in the package license field name..
=> upgrade dependencies

src/openapi/transport/retry.js, test/unit/openapi/transport/retry-spec.js
Extends the TransportRetry to also apply to successful requests that returned a given status code (e.g. 504 Gateway timeout). Adds custom timeouts configuration to individual method option.
=> add options of status codes and custom timeouts to TransportRetry

src/openapi/streaming/streaming.js, src/openapi/streaming/subscription-actions.js, src/openapi/streaming/subscription-queue.js, src/openapi/streaming/subscription.js, src/utils/object.js, test/unit/openapi/streaming/streaming-spec.js, test/unit/openapi/streaming/subscription-queue-spec.js, test/unit/openapi/streaming/subscription-spec.js
1. Unsubscribe on reset.
2. Patch on modify with options
=>  #749180. Delete on reset, modify patch.

src/openapi/transport/core.js, test/unit/openapi/transport/core-spec.js
=> fixed language header

package.json, src/openapi/streaming/streaming.js, src/openapi/streaming/subscription-actions.js, src/openapi/streaming/subscription-queue.js, src/openapi/streaming/subscription.js, test/unit/openapi/streaming/streaming-spec.js, test/unit/openapi/streaming/subscription-queue-spec.js, test/unit/openapi/streaming/subscription-spec.js
=> Add functionality to unsubscribe by tag

package.json, src/openapi/streaming/serializer/wrappers/protobuf-wrappers.js, test/unit/mocks/proto-price.js, test/unit/openapi/serializer/serializer-protobuf-spec.js
Relates to any timestamp given that should be comparable by nano precision.
=> Adding nanoprecision to protobuf timestamp response

changelog.md, package.json, src/micro-emitter.js, src/openapi/streaming/orphan-finder.js, src/openapi/streaming/streaming.js, src/openapi/streaming/subscription.js, src/openapi/transport/batch.js, src/openapi/transport/queue.js
because
1. reading past the end of an array causes a v8 deopt
2. its not a normal style
=> Fix for-style to one without performance problems thats more normal

src/openapi/streaming/streaming.js
Reverts SaxoBank/openapi-clientlib-js#44
=> Revert "Clear reconnect timeout "

src/openapi/streaming/streaming.js, src/openapi/streaming/subscription.js
=> Fix warnings about data on subscriptions

src/openapi/transport/core.spec.js, src/utils/fetch.js
GET doesn't support body and also it should be undefined not  null.
ref: https://github.com/github/fetch/issues/402
=> body other than PATCH default to undefined

src/price-formatting/format.js, src/price-formatting/format.spec.js
Please track the discussion here #96
=> propose to remove space before %

src/openapi/streaming/subscription.js
Adds the subscription state values on the Subscription prototype so that they can be accessed on the object and be used to compare with currentState.
=> Add state constants to subscription prototype

package-lock.json, package.json
=> babel, rollup, jest upgrades

.eslintrc, changelog.md, package.json, src/openapi-package.js, src/openapi/transport/putPatchDiagnosticsQueue.js, src/openapi/transport/putPatchDiagnosticsQueue.spec.js, src/openapi/transport/queue.js, src/test/mocks/transport.js
* Only blocks put/patch requests unlike queue
* Includes the calls and logic to make the requests and switch to POST mode
=> Add putPatchDiagnoticsQueue

changelog.md, package-lock.json, package.json, src/openapi/streaming/connection/connection.js, src/openapi/streaming/connection/transport/websocket-transport.js, src/openapi/streaming/subscription.js
Add more data in error logs to make it easier to investigate related issues.
=> Improve logging around streaming

.gitignore, README.md, package-lock.json, package.json
Now that http://doclets.io appear to be out of service, this PR provides a simple way to build and browse the documentation locally.
Feel free to tweak, happy to discuss this.
=> Document how to build and view the documentation

src/number-formatting/format.js, src/price-formatting/format.spec.js
This reverts commit b483386c2afbce0acbd765641ae347141ce52412.
=> Revert "Bug fix rounding decimals formatters (#304)"

changelog.md, package-lock.json, package.json, src/openapi/streaming/connection/connection.js, src/openapi/streaming/connection/constants.js, src/openapi/streaming/connection/transport/signalr-core-transport.js, src/openapi/streaming/connection/transport/signalr-core-transport.spec.js, src/openapi/streaming/connection/transport/websocket-transport.js, src/openapi/streaming/connection/transport/websocket-transport.spec.js, src/openapi/streaming/streaming.js, src/openapi/streaming/streaming.spec.js, src/openapi/streaming/subscription-queue.js, src/openapi/streaming/subscription.js, src/openapi/transport/core.js
see https://github.com/SaxoBank/openapi-clientlib-js/pull/334
merged into the wrong branch.
=> Fix streaming issues

changelog.md, src/openapi/transport/core.spec.ts, src/openapi/transport/core.ts, src/types.ts, src/utils/fetch.ts
This PR migrates the recent feature from master (#393) to TypeScript
=> Migrate PR #393 to TS

changelog.md, package.json, src/openapi/streaming/streaming.ts
Copy since I don't have permission to push to @robatwilliams fork #448
Adds message count and last message received datetime on disconnection.
=> Message count log

src/openapi/streaming/subscription.spec.ts, src/openapi/streaming/subscription.ts
When we get a reset on the subscription, we re-subscribe.
However we have seen in the past that when open api is in a bad state, they may reset immediately.
So we would like to detect if we get a 3rd reset within 1 minute that we
1) Log an error
2) wait a minute
and obviously if unsubscribe occurs whilst waiting then it shouldn't resume.
=> wait 1 minute when 3 resets received within a minute

package-lock.json, package.json, src/openapi/streaming/connection/transport/signalr-core-transport.ts
=> Bearer duplicate error

changelog.md, package-lock.json, package.json, src/openapi/streaming/connection/transport/websocket-transport.ts, src/utils/fetch.spec.ts, src/utils/fetch.ts
- Unexpected state onAuthorized
Happening alot and is not actually a problem, added comment
- Falling back to content type text
Fixed the common cases - no content length and text/html
=> Fixes for excessive logging

changelog.md, package-lock.json, package.json, src/openapi/streaming/streaming.ts, src/openapi/streaming/subscription.ts
A number of errors occur on live and I cannot work out how they occur - I need more context.
So I have added a internal log of what happens on a subscription and I have attached it to the log errors I am uncertain about.
=> Add diagnostics to try and work out how unexpected states can occur
